<?php 
$config['rss_feeds'] = array(
  array(
    'id' => 'sci_toc',
    'publication' => 'sci',
    'description' => 'The best in science news, commentary, and research',
    'data_source' => 'Articles',
    'name' => 'Science: Current Issue',
    'abstract' => 'teaser',
    'filters' => array(),
    'sort' => 'fpage',
    'output' => APPPATH."output/rss/current.xml",
  ),
  array(
    'id' => 'sci_editorschoice',
    'publication' => 'sci',
    'description' => 'Highlights of the recent literature, from the editors of Science Magazine',
    'data_source' => 'Articles',
    'abstract' => 'main',
    'name' => 'Science Editors\' Choice',
    'filters' => array(
      'article_type' => 'editors\' choice',
    ),
    'sort' => 'fpage',
    'output' => APPPATH.'output/rss/ec.xml',
  ),
  array(
    'id' => 'sci_news',
    'publication' => 'sci',
    'description' => 'Summaries of this week\'s top stories, from Science Magazine',
    'data_source' => 'Articles',
    'name' => 'Science: Current Issue',
    'filters' => array(
      'article_type' => 'news'
    ),
    'sort' => 'fpage',
    'output' => APPPATH. 'output/rss/news.xml',
  ),
  array(
    'id' => 'sci_express',
    'publication' => 'sci',
    'description' => 'Online publication of Science papers, in advance of print publication',
    'data_source' => 'ScienceXpress',
    'name' => 'Science Express TOC RSS Feed',
    'filters' => array(),
    'sort' => 'fpage',
    'output' => APPPATH. 'output/rss/express.xml',
  ),
  array(
    'id' => 'sci_twis',
    'publication' => 'sci',
    'description' => 'Research highlights from the current issue of Science Magazine',
    'data_source' => 'ScienceXpress',
    'name' => 'Science This Week in Science TOC RSS Feed',
    'filters' => array(),
    'sort' => 'fpage',
    'output' => APPPATH. 'output/rss/twis.xml',
  ),
  array(
    'id' => 'stm_toc',
    'publication' => 'stm',
    'data_source' => 'Articles',
    'name' => 'Science STM TOC RSS Feed',
    'filters' => array(),
    'sort' => 'fpage',
    'output' => APPPATH. 'output/rss/stm.xml',
  ),
  array(
    'id' => 'sig_toc',
    'publication' => 'sig',
    'data_source' => 'Articles',
    'name' => 'Science Signaling TOC RSS Feed',
    'filters' => array(),
    'sort' => 'fpage',
    'output' => APPPATH. 'output/rss/sig.xml',
  ),
);
